import type { Metadata } from "next";
import NavBar from "./components/shared/Navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <NavBar></NavBar>
      <div className="mx-auto container">{children}</div>
      <p>footer</p>
    </div>
  );
}
